# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ef9bd2a05ba91a7a123e75f93142ef85e65f0beb3030aab7e7e161dd48c462581b7b3fd8ffcc10dbbd5fb4a9d1f7b8401c5a199a0ad29571185e0f7ec3d17e4

test:
  secret_key_base: bb6dfc1994e1f3d8e77de06b50391594214c52a6573aa6722f69a6c8bb52076fa0ddbf79f42a5f5883413065a46510e930fa599705da46b55aabf55d805fbf2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
